[package]
name = "bevy_egui_app"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17"
bevy_egui = "0.38"
egui_dock = { path = "egui_dock", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
